# Generated by Django 6.1.2 on 2026-10-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={"ordering": ["-created_at"], "verbose_name_plural": "equipment"},
        ),
    ]
