# Generated by Django 5.0 on 2024-12-20 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.DecimalField(decimal_places=2, help_text='Size in acres', max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('soil_type', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irrigation_type', models.CharField(choices=[('drip', 'Drip Irrigation'), ('sprinkler', 'Sprinkler System'), ('flood', 'Flood Irrigation'), ('center_pivot', 'Center Pivot'), ('other', 'Other')], max_length=20)),
                ('installation_date', models.DateField()),
                ('water_source', models.CharField(max_length=100)),
                ('flow_rate', models.DecimalField(decimal_places=2, help_text='Flow rate in gallons per minute', max_digits=8)),
                ('coverage_area', models.DecimalField(decimal_places=2, help_text='Coverage area in acres', max_digits=10)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_systems', to='land_management.field')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], max_length=10)),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('water_amount', models.DecimalField(decimal_places=2, help_text='Amount in gallons', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('irrigation_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='land_management.irrigationsystem')),
            ],
        ),
        migrations.CreateModel(
            name='SoilAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nitrogen_level', models.DecimalField(decimal_places=2, help_text='N content in ppm', max_digits=5)),
                ('phosphorus_level', models.DecimalField(decimal_places=2, help_text='P content in ppm', max_digits=5)),
                ('potassium_level', models.DecimalField(decimal_places=2, help_text='K content in ppm', max_digits=5)),
                ('organic_matter', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_analyses', to='land_management.field')),
            ],
            options={
                'verbose_name_plural': 'Soil analyses',
                'ordering': ['-test_date'],
            },
        ),
    ]
