# Generated by Django 6.1.2 on 2026-10-06 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="tag_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("owner", "tag_number"),
                name="unique_active_tag_per_owner",
            ),
        ),
    ]
